### ISSUE TITLE
写入xml就会无法启用

### ISSUE THREAD

**Issue by hackerjmss** [fluttercandies/flutter_bdface_collect#32]
### Version

1.1.4

### Platforms

Android

### Device Model

安卓模拟器

### flutter info

```sh
<!--将com.baidu.idl.face.demo替换成您工程的包名-->
        <provider android:authorities="com.zhiling.app.liantian.ac.provider"
                  android:name="com.baidu.liantian.LiantianProvider" android:exported="true"/>

只要在xml中写这个，就会无法启用，错误信息如下
```

### How to reproduce?

        <provider android:authorities="com.zhiling.app.liantian.ac.provider"
                  android:name="com.baidu.liantian.LiantianProvider" android:exported="true"/>

只要在xml中写这个，就会无法启用，错误信息如下

### Logs

```sh
Launching lib\main.dart on DLT A0 in debug mode...
main.dart:1
√  Built build\app\outputs\flutter-apk\app-debug.apk.
E/AndroidRuntime(18919): FATAL EXCEPTION: main
E/AndroidRuntime(18919): Process: com.zhiling.app, PID: 18919
E/AndroidRuntime(18919): java.lang.RuntimeException: Unable to get provider com.baidu.liantian.LiantianProvider: java.lang.ClassNotFoundException: Didn't find class "com.baidu.liantian.LiantianProvider" on path: DexPathList[[zip file "/data/app/com.zhiling.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zhiling.app-1/lib/x86, /data/app/com.zhiling.app-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
E/AndroidRuntime(18919): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5934)
E/AndroidRuntime(18919): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5523)
E/AndroidRuntime(18919): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5462)
E/AndroidRuntime(18919): 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
E/AndroidRuntime(18919): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
E/AndroidRuntime(18919): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(18919): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(18919): 	at android.app.ActivityThread.main(ActivityThread.java:6197)
E/AndroidRuntime(18919): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18919): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
E/AndroidRuntime(18919): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
E/AndroidRuntime(18919): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.baidu.liantian.LiantianProvider" on path: DexPathList[[zip file "/data/app/com.zhiling.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zhiling.app-1/lib/x86, /data/app/com.zhiling.app-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
E/AndroidRuntime(18919): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(18919): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
E/AndroidRuntime(18919): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(18919): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5919)
E/AndroidRuntime(18919): 	... 10 more
```

**Comment by CyJaySong** [comment]
不需要写入呀，直接按照readme弄就完了
