### ISSUE TITLE
安卓初始化报错

### ISSUE THREAD

**Issue by dnoaius** [fluttercandies/flutter_bdface_collect#40]
### Version

1.1.8

### Platforms

dart

### Device Model

Android 11

### flutter info

```sh
[!] Flutter (Channel unknown, 3.10.0, on Microsoft Windows [版本 10.0.19045.3208], locale zh-CN)
    ! Flutter version 3.10.0 on channel unknown at D:\Flutter\SDK\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision 84a1e904f4 (2 months ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\AndroidStudio\SDK
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: D:\AndroidStudio\to\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio 15 生成工具 2017 15.9.55)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio 15 生成工具 2017 version 15.9.33801.237
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at D:\AndroidStudio\to
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (4 available)
    • ELE AL00 (mobile) • 8KE0219423003518 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [版本 10.0.19045.3208]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 113.0.5672.129
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 114.0.1823.82

[√] Network resources
    • All expected network resources are available.
```

### How to reproduce?

调试环境报错可以初始化成功，打包之后初始化app直接闪退了 

### Logs

```sh
W/System.err(23459): java.lang.ClassNotFoundException: Didn't find class "com.baidu.liantian.ac.LH" on path: DexPathList[[zip file "/data/app/com.czyhqc.qczn-oHMyoUrpAZN2jVsszfg9Iw==/base.apk"],nativeLibraryDirectories=[/data/app/com.czyhqc.qczn-oHMyoUrpAZN2jVsszfg9Iw==/lib/arm64, /data/app/com.czyhqc.qczn-oHMyoUrpAZN2jVsszfg9Iw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]
W/System.err(23459): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
W/System.err(23459): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err(23459): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err(23459): 	at com.baidu.vis.unified.license.AndroidLicenser.getDeviceId(AndroidLicenser.java:63)
W/System.err(23459): 	at com.baidu.vis.unified.license.AndroidLicenser.nativeFaceAuthFromFile(Native Method)
W/System.err(23459): 	at com.baidu.vis.unified.license.AndroidLicenser.authFromFile(AndroidLicenser.java:114)
W/System.err(23459): 	at com.baidu.idl.main.facesdk.FaceAuth$1.run(FaceAuth.java:121)
W/System.err(23459): 	at com.baidu.idl.main.facesdk.FaceQueue$PoolWorker.run(FaceQueue.java:51)
I/License-SDK(23459): Load liantian ac failed
E/License-SDK(23459): read_license_from_system_path FileNotFoundException
W/System.err(23459): java.io.FileNotFoundException: /sdcard/bd_license_request_url.txt: open failed: ENOENT (No such file or directory)
W/System.err(23459): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(23459): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err(23459): 	at com.baidu.vis.unified.license.LicenseReaderUtils.read_license_from_system_path(LicenseReaderUtils.java:54)
W/System.err(23459): 	at com.baidu.vis.unified.license.LicenseReaderUtils.get_local_license_file_inputstream(LicenseReaderUtils.java:38)
W/System.err(23459): 	at com.baidu.vis.unified.license.LicenseNewReader.readFile(LicenseNewReader.java:48)
W/System.err(23459): 	at com.baidu.vis.unified.license.AndroidLicenser.nativeFaceAuthFromFile(Native Method)
W/System.err(23459): 	at com.baidu.vis.unified.license.AndroidLicenser.authFromFile(AndroidLicenser.java:114)
W/System.err(23459): 	at com.baidu.idl.main.facesdk.FaceAuth$1.run(FaceAuth.java:121)
W/System.err(23459): 	at com.baidu.idl.main.facesdk.FaceQueue$PoolWorker.run(FaceQueue.java:51)
W/System.err(23459): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err(23459): 	at libcore.io.Linux.open(Native Method)
W/System.err(23459): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(23459): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(23459): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(23459): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8469)
W/System.err(23459): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(23459): 	... 8 more
E/License-SDK(23459): read_license_from_asset
E/License-SDK(23459): read_license_from_asset IOException
W/System.err(23459): java.io.FileNotFoundException: /sdcard/bd_license_request_url.txt
W/System.err(23459): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
W/System.err(23459): 	at android.content.res.AssetManager.open(AssetManager.java:942)
W/System.err(23459): 	at android.content.res.AssetManager.open(AssetManager.java:919)
W/System.err(23459): 	at com.baidu.vis.unified.license.LicenseReaderUtils.read_license_from_asset(LicenseReaderUtils.java:99)
W/System.err(23459): 	at com.baidu.vis.unified.license.LicenseReaderUtils.get_local_license_file_inputstream(LicenseReaderUtils.java:45)
W/System.err(23459): 	at com.baidu.vis.unified.license.LicenseNewReader.readFile(LicenseNewReader.java:48)
W/System.err(23459): 	at com.baidu.vis.unified.license.AndroidLicenser.nativeFaceAuthFromFile(Native Method)
W/System.err(23459): 	at com.baidu.vis.unified.license.AndroidLicenser.authFromFile(AndroidLicenser.java:114)
W/System.err(23459): 	at com.baidu.idl.main.facesdk.FaceAuth$1.run(FaceAuth.java:121)
W/System.err(23459): 	at com.baidu.idl.main.facesdk.FaceQueue$PoolWorker.run(FaceQueue.java:51)
E/License-SDK(23459): open license file error.
E/License-SDK(23459): license file info
```

**Comment by dnoaius** [comment]
解决了，原来打包要关闭混淆才可以
