### ISSUE TITLE
华为荣耀android8系统，调用人脸采集闪退

### ISSUE THREAD

**Issue by aiqianqianli** [fluttercandies/flutter_bdface_collect#43]
### Version

1.1.8

### Platforms

dart, Android

### Device Model

华为荣耀android8

### flutter info

```sh
[✓] Flutter (Channel stable, 3.13.0, on macOS 12.6.3 21G419 darwin-arm64 (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.13.0 on channel stable at /Users/nanhaichao/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (3 weeks ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nanhaichao/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.3)
    • VS Code at /Users/nanhaichao/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • DUA AL00 (mobile) • HFK9K18803907705 • android-arm64  • Android 8.1.0 (API 27)
    • macOS (desktop)   • macos            • darwin-arm64   • macOS 12.6.3 21G419 darwin-arm64 (Rosetta)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.
```

### How to reproduce?

调用人脸采集方法CollectResult res = await FlutterBdfaceCollect.instance.collect(FaceConfig(
              scale: 0.7,
              livenessTypes: Set.from(LivenessType.all.sublist(0, 1))));

### Logs

```sh
V/jhw     (32532): call Intent.migrateExtraStreamToClipData(1)
D/WifiManager(32532): startScan, uid:10107
D/BrightnessUtils(32532): set  lp.screenBrightness == 1.392157
W/way.zhxl.common(32532): type=1400 audit(0.0:7792): avc: denied { search } for name="clients" dev="debugfs" ino=7268 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:debugfs_ion:s0 tclass=dir permissive=0
D/skia    (32532): SkJpegCodec::onGetPixels + (1081, 510)
D/skia    (32532): SkJpegCodec::onGetPixels -
D/CubicBezierInterpolator(32532): CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
D/CubicBezierInterpolator(32532): CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
D/CubicBezierInterpolator(32532): CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
D/CubicBezierInterpolator(32532): CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
D/CubicBezierInterpolator(32532): CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
D/CubicBezierInterpolator(32532): CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
D/CubicBezierInterpolator(32532): CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
D/CubicBezierInterpolator(32532): CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
D/HwRTBlurUtils(32532): check blur style for HwPhoneWindow, themeResId : 0x7f120251, context : com.fluttercandies.flutter_bdface_collect.FaceDetectActivity@e302cb5, Nhwext : 0, get Blur : disable with , null
D/Camera-JNI(32532): (tid:32532)[MtkJNICameraContext] this:0x77f767ad60 camera->getStrongCount(3) 
D/Camera  (32532): app passed NULL surface
V/PhoneWindow(32532): DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@73ce68f[]
D/WindowClient(32532): Add to mViews: DecorView@73ce68f[FaceDetectActivity], this = android.view.WindowManagerGlobal@85f83cf
D/ViewRootImpl[FaceDetectActivity](32532): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
V/PhoneWindow(32532): DecorView setVisiblity: visibility = 0, Parent = ViewRoot{2372efa com.lntransway.zhxl.common/com.fluttercandies.flutter_bdface_collect.FaceDetectActivity,ident = 1}, this = DecorView@73ce68f[FaceDetectActivity]
D/Surface (32532): Surface::connect(this=0x77c8daf000,api=1)
D/Camera-JNI(32532): (tid:32566)[~MtkJNICameraContext] this:0x77f767ad60 
D/Camera-JNI(32532): (tid:32532)[MtkJNICameraContext] this:0x77f7678600 camera->getStrongCount(3) 
I/Choreographer(32532): Skipped 48 frames!  The application may be doing too much work on its main thread.
D/HWUIExtension(32532): MTKProgramCache.generateProgram: 1099511627784
D/HWUIExtension(32532): createProgram 0x0000010000000008, binary 0x77cdc8a2d2, length 13254, format 37168 within 14555ns
D/HWUIExtension(32532): MTKProgramCache.generateProgram: 562949953421313
D/HWUIExtension(32532): createProgram 0x0002000000000001, binary 0x77cdc7c31b, length 11553, format 37168 within 766ns
D/HWUIExtension(32532): MTKProgramCache.generateProgram: 633318697598977
D/HWUIExtension(32532): MTKProgramCache.generateProgram: 70368744177665
D/HWUIExtension(32532): MTKProgramCache.generateProgram: 562984313159683
D/HWUIExtension(32532): createProgram 0x0002000800000003, binary 0x77cdc87603, length 11471, format 37168 within 1149ns
I/Camera  (32532): handleMessage: 16
D/AndroidRuntime(32532): Shutting down VM
E/AndroidRuntime(32532): FATAL EXCEPTION: main
E/AndroidRuntime(32532): Process: com.lntransway.zhxl.common, PID: 32532
E/AndroidRuntime(32532): java.lang.RuntimeException: Camera is being used after Camera.release() was called
E/AndroidRuntime(32532):        at android.hardware.Camera.setHasPreviewCallback(Native Method)
E/AndroidRuntime(32532):        at android.hardware.Camera.-wrap2(Unknown Source:0)
E/AndroidRuntime(32532):        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1165)
E/AndroidRuntime(32532):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(32532):        at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(32532):        at android.app.ActivityThread.main(ActivityThread.java:6861)
E/AndroidRuntime(32532):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32532):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
E/AndroidRuntime(32532):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process (32532): Sending signal. PID: 32532 SIG: 9
Lost connection to device.
```

### Example code (optional)

```Dart
CollectResult res = await FlutterBdfaceCollect.instance.collect(FaceConfig(
              scale: 0.7,
              livenessTypes: Set.from(LivenessType.all.sublist(0, 1))));
```

### Contact

472762840@qq.com

**Comment by CyJaySong** [comment]
估计是不兼容，我看到百度SDK有更新，我下周抽时间更新一下

**Comment by CyJaySong** [comment]
SDK 并没有更新，只是他们的UI更新了而已
